### ISSUE TITLE
MNase-seq like datasets

### ISSUE THREAD

**Issue by avilella** [zentnerlab/chec-seq#1]
Is this a software to try for MNase-like datasets that would give me a per-position score combining read depth + insert size + nucleosome positioning information?
This is mentioned in the README of the repo, but it seems from the Nature Comms paper that CHEC-seq relies on different points of temporal information for the same sample.

**Comment by zentnerlab** [comment]
Hi Albert, 

You could in principle use some of these programs for MNase-seq-type datasets, though there is no function for looking at nucleosome centers. You could use pairs2bedgraph.pl and restrict the insert size to, say, 140-160 bp to get nucleosome-size fragments. Just need to convert a SAM file to PAIRS. I've attached our in-house Ruby script for doing that. Let me know if this makes sense/works for you.

Best,
Gabe

[sam_to_pairs_v0.1.rb.zip](https://github.com/zentnerlab/chec-seq/files/1359888/sam_to_pairs_v0.1.rb.zip)
